# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'training.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etraining.proto\"C\n\x08Training\x12\x1b\n\x04meta\x18\x01 \x01(\x0b\x32\r.TrainingMeta\x12\x1a\n\x04logs\x18\x02 \x03(\x0b\x32\x0c.TrainingLog\"\xc7\x01\n\x0cTrainingMeta\x12\x12\n\nstart_time\x18\x01 \x01(\x04\x12\x10\n\x08\x64uration\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\r\x12\x1b\n\x04type\x18\x04 \x01(\x0e\x32\r.TrainingType\x12\x1b\n\x04mode\x18\x05 \x01(\x0e\x32\r.TrainingMode\x12\x16\n\x0esplit_distance\x18\x06 \x01(\r\x12\x15\n\rrest_duration\x18\x07 \x01(\r\x12\x0f\n\x02id\x18\x63 \x01(\tH\x00\x88\x01\x01\x42\x05\n\x03_id\"2\n\x0bGPSPosition\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\"\x87\x01\n\x0bTrainingLog\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\r\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x12\n\nstrokerate\x18\x03 \x01(\r\x12\x11\n\theartrate\x18\x04 \x01(\r\x12#\n\x08position\x18\x05 \x01(\x0b\x32\x0c.GPSPositionH\x00\x88\x01\x01\x42\x0b\n\t_position*>\n\x0cTrainingType\x12\x0c\n\x08\x44ISTANCE\x10\x00\x12\x08\n\x04TIME\x10\x01\x12\x0c\n\x08INTERVAL\x10\x02\x12\x08\n\x04\x46REE\x10\x03*\'\n\x0cTrainingMode\x12\n\n\x06ROWING\x10\x00\x12\x0b\n\x07\x43YCLING\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGTYPE']._serialized_start=479
  _globals['_TRAININGTYPE']._serialized_end=541
  _globals['_TRAININGMODE']._serialized_start=543
  _globals['_TRAININGMODE']._serialized_end=582
  _globals['_TRAINING']._serialized_start=18
  _globals['_TRAINING']._serialized_end=85
  _globals['_TRAININGMETA']._serialized_start=88
  _globals['_TRAININGMETA']._serialized_end=287
  _globals['_GPSPOSITION']._serialized_start=289
  _globals['_GPSPOSITION']._serialized_end=339
  _globals['_TRAININGLOG']._serialized_start=342
  _globals['_TRAININGLOG']._serialized_end=477
# @@protoc_insertion_point(module_scope)
